#!/bin/bash

# Author: Michal Kukowski
# email: michalkukowski10@gmail.com

# Full path of this script
THIS_DIR=`readlink -f "${BASH_SOURCE[0]}" 2>/dev/null||echo $0`

# This directory path
DIR=`dirname "${THIS_DIR}"`

# NArgs File

nargs_file="${DIR}/../inc/kmacros/knargs.h"

rm -f ${nargs_file}
touch ${nargs_file}
echo \
"#ifndef KNARGS_H
#define KNARGS_H

/*
    This is the private header for the KMacros.

    This header contains simple trick to calculate __VA_ARGS__

    Do not include it directly

    Author: Michal Kukowski
    email: michalkukowski10@gmail.com
    LICENCE: GPL3

    This file has been generated by script: knargs_create.sh
    DO NOT EDIT THIS FILE
*/

#ifndef KMACROS_H
#error \"Never include <kmacros/knargs.h> directly, use <kmacros/kmacros.h> instead.\"
#endif
" >> ${nargs_file}

echo -n "#define KNARGS_PRIV(" >> ${nargs_file}

for ((i=0; i<10; i++));
do
    for ((j=1; j<11; j++));
    do
        n=$((i * 10 + j))
        echo -n "_${n}, " >> ${nargs_file}
    done
    echo "\\" >> ${nargs_file}
    echo -n "                    " >> ${nargs_file}
done
echo "_N, ...) _N" >> ${nargs_file}

echo "" >> ${nargs_file}
echo "" >> ${nargs_file}

echo -n "#define KNARGS(...) KNARGS_PRIV(__VA_ARGS__, " >> ${nargs_file}
for ((i=9; i>=0; i--));
do
    echo "\\" >> ${nargs_file}
    echo -n "                                " >> ${nargs_file}
    for ((j=10; j>0; j--));
    do
        n=$((i * 10 + j))
        echo -n "${n}" >> ${nargs_file}
        if ! { [ $i -eq 0 ] && [ $j -eq 1 ]; }; then
            echo -n ", " >> ${nargs_file}
        fi
    done
done

echo ")" >> ${nargs_file}
echo "" >> ${nargs_file}

echo \
"#endif" >> ${nargs_file}