#ifndef KTERMINAL_COLORS_H
#define KTERMINAL_COLORS_H

/*
    This is the private header for the KMacros.

    This file defined some escaped chars for terminal fonts (color, bold, italic, underline, background)

    Do not include it directly

    Author: Michal Kukowski
    email: michalkukowski10@gmail.com
    LICENCE: GPL3
*/

#ifndef KMACROS_H
#error "Never include <kmacros/kterminal-colors.h> directly, use <kmacros/kmacros.h> instead."
#endif

#include "kpreprocessor.h"

/**
 * Create full formated string using escape chars supported by terminals
 *
 * @param[in] str        - string to format
 * @param[in] color      - one of the KTERMINAL_FONT_COLOR_STR_
 * @param[in] background - one of the KTERMINAL_BG_COLOR_STR_
 * @param[in] attr       - one of the KTERMINAL_FORMAT_ATTR_STR_
 */
#define KTERMINAL_CREATE_FORMATTED_STRING(str, color, background, attr) \
    "\033[" color ";" background ";" attr "m" str "\033[" KTERMINAL_RESET_STR_ALL "m"

/**
 * Create colorful formated string using escape chars supported by terminals
 *
 * @param[in] str        - string to format
 * @param[in] color      - one of the KTERMINAL_FONT_COLOR_STR_
 */
#define KTERMINAL_CREATE_COLORFUL_STRING(str, color) \
        "\033[" color "m" str "\033[" KTERMINAL_RESET_STR_ALL "m"

/**
 * Create colorful formated string with background using escape chars supported by terminals
 *
 * @param[in] str        - string to format
 * @param[in] color      - one of the KTERMINAL_FONT_COLOR_STR_
 * @param[in] background - one of the KTERMINAL_BG_COLOR_STR_
 */
#define KTERMINAL_CREATE_COLORFUL_BG_STRING(str, color, background) \
        "\033[" color ";" background "m"  str "\033[" KTERMINAL_RESET_STR_ALL "m"

/* INT section, FONT COLOR */
#define KTERMINAL_FONT_COLOR_INT_DEFAULT     39
#define KTERMINAL_FONT_COLOR_INT_BLACK       30
#define KTERMINAL_FONT_COLOR_INT_RED         31
#define KTERMINAL_FONT_COLOR_INT_GREEN       32
#define KTERMINAL_FONT_COLOR_INT_YELLOW      33
#define KTERMINAL_FONT_COLOR_INT_BLUE        34
#define KTERMINAL_FONT_COLOR_INT_MAGENTA     35
#define KTERMINAL_FONT_COLOR_INT_CYAN        36
#define KTERMINAL_FONT_COLOR_INT_LGRAY       37
#define KTERMINAL_FONT_COLOR_INT_DGRAY       90
#define KTERMINAL_FONT_COLOR_INT_LRED        91
#define KTERMINAL_FONT_COLOR_INT_LGREEN      92
#define KTERMINAL_FONT_COLOR_INT_LYELLOW     93
#define KTERMINAL_FONT_COLOR_INT_LBLUE       94
#define KTERMINAL_FONT_COLOR_INT_LMAGENTA    95
#define KTERMINAL_FONT_COLOR_INT_LCYAN       96
#define KTERMINAL_FONT_COLOR_INT_WHITE       97

/* INT section, BACKGROUND COLOR */
#define KTERMINAL_BG_COLOR_INT_DEFAULT       49
#define KTERMINAL_BG_COLOR_INT_BLACK         40
#define KTERMINAL_BG_COLOR_INT_RED           41
#define KTERMINAL_BG_COLOR_INT_GREEN         42
#define KTERMINAL_BG_COLOR_INT_YELLOW        43
#define KTERMINAL_BG_COLOR_INT_BLUE          44
#define KTERMINAL_BG_COLOR_INT_MAGENTA       45
#define KTERMINAL_BG_COLOR_INT_CYAN          46
#define KTERMINAL_BG_COLOR_INT_LGRAY         47
#define KTERMINAL_BG_COLOR_INT_DGRAY         100
#define KTERMINAL_BG_COLOR_INT_LRED          101
#define KTERMINAL_BG_COLOR_INT_LGREEN        102
#define KTERMINAL_BG_COLOR_INT_LYELLOW       103
#define KTERMINAL_BG_COLOR_INT_LBLUE         104
#define KTERMINAL_BG_COLOR_INT_LMAGENTA      105
#define KTERMINAL_BG_COLOR_INT_LCYAN         106
#define KTERMINAL_BG_COLOR_INT_WHITE         107

/* INT section, FORMAT ATTRIBUTES COLOR */
#define KTERMINAL_FORMAT_ATTR_INT_DEFAULT    0
#define KTERMINAL_FORMAT_ATTR_INT_BOLD       1
#define KTERMINAL_FORMAT_ATTR_INT_DIM        2
#define KTERMINAL_FORMAT_ATTR_INT_UNDERLINED 3
#define KTERMINAL_FORMAT_ATTR_INT_BLINK      4

#define KTERMINAL_RESET_INT_ALL              0

/* STR section, FONT COLOR */
#define KTERMINAL_FONT_COLOR_STR_DEFAULT     KTOSTRING(KTERMINAL_FONT_COLOR_INT_DEFAULT)
#define KTERMINAL_FONT_COLOR_STR_BLACK       KTOSTRING(KTERMINAL_FONT_COLOR_INT_BLACK)
#define KTERMINAL_FONT_COLOR_STR_RED         KTOSTRING(KTERMINAL_FONT_COLOR_INT_RED)
#define KTERMINAL_FONT_COLOR_STR_GREEN       KTOSTRING(KTERMINAL_FONT_COLOR_INT_GREEN)
#define KTERMINAL_FONT_COLOR_STR_YELLOW      KTOSTRING(KTERMINAL_FONT_COLOR_INT_YELLOW)
#define KTERMINAL_FONT_COLOR_STR_BLUE        KTOSTRING(KTERMINAL_FONT_COLOR_INT_BLUE)
#define KTERMINAL_FONT_COLOR_STR_MAGENTA     KTOSTRING(KTERMINAL_FONT_COLOR_INT_MAGENTA)
#define KTERMINAL_FONT_COLOR_STR_CYAN        KTOSTRING(KTERMINAL_FONT_COLOR_INT_CYAN)
#define KTERMINAL_FONT_COLOR_STR_LGRAY       KTOSTRING(KTERMINAL_FONT_COLOR_INT_LGRAY)
#define KTERMINAL_FONT_COLOR_STR_DGRAY       KTOSTRING(KTERMINAL_FONT_COLOR_INT_DGRAY)
#define KTERMINAL_FONT_COLOR_STR_LRED        KTOSTRING(KTERMINAL_FONT_COLOR_INT_LRED)
#define KTERMINAL_FONT_COLOR_STR_LGREEN      KTOSTRING(KTERMINAL_FONT_COLOR_INT_LGREEN)
#define KTERMINAL_FONT_COLOR_STR_LYELLOW     KTOSTRING(KTERMINAL_FONT_COLOR_INT_LYELLOW)
#define KTERMINAL_FONT_COLOR_STR_LBLUE       KTOSTRING(KTERMINAL_FONT_COLOR_INT_LBLUE)
#define KTERMINAL_FONT_COLOR_STR_LMAGENTA    KTOSTRING(KTERMINAL_FONT_COLOR_INT_LMAGENTA)
#define KTERMINAL_FONT_COLOR_STR_LCYAN       KTOSTRING(KTERMINAL_FONT_COLOR_INT_LCYAN)
#define KTERMINAL_FONT_COLOR_STR_WHITE       KTOSTRING(KTERMINAL_FONT_COLOR_INT_WHITE)

/* STR section, BACKGROUND COLOR */
#define KTERMINAL_BG_COLOR_STR_DEFAULT       KTOSTRING(KTERMINAL_BG_COLOR_INT_DEFAULT)
#define KTERMINAL_BG_COLOR_STR_BLACK         KTOSTRING(KTERMINAL_BG_COLOR_INT_BLACK)
#define KTERMINAL_BG_COLOR_STR_RED           KTOSTRING(KTERMINAL_BG_COLOR_INT_RED)
#define KTERMINAL_BG_COLOR_STR_GREEN         KTOSTRING(KTERMINAL_BG_COLOR_INT_GREEN)
#define KTERMINAL_BG_COLOR_STR_YELLOW        KTOSTRING(KTERMINAL_BG_COLOR_INT_YELLOW)
#define KTERMINAL_BG_COLOR_STR_BLUE          KTOSTRING(KTERMINAL_BG_COLOR_INT_BLUE)
#define KTERMINAL_BG_COLOR_STR_MAGENTA       KTOSTRING(KTERMINAL_BG_COLOR_INT_MAGENTA)
#define KTERMINAL_BG_COLOR_STR_CYAN          KTOSTRING(KTERMINAL_BG_COLOR_INT_CYAN)
#define KTERMINAL_BG_COLOR_STR_LGRAY         KTOSTRING(KTERMINAL_BG_COLOR_INT_LGRAY)
#define KTERMINAL_BG_COLOR_STR_DGRAY         KTOSTRING(KTERMINAL_BG_COLOR_INT_DGRAY)
#define KTERMINAL_BG_COLOR_STR_LRED          KTOSTRING(KTERMINAL_BG_COLOR_INT_LRED)
#define KTERMINAL_BG_COLOR_STR_LGREEN        KTOSTRING(KTERMINAL_BG_COLOR_INT_LGREEN)
#define KTERMINAL_BG_COLOR_STR_LYELLOW       KTOSTRING(KTERMINAL_BG_COLOR_INT_LYELLOW)
#define KTERMINAL_BG_COLOR_STR_LBLUE         KTOSTRING(KTERMINAL_BG_COLOR_INT_LBLUE)
#define KTERMINAL_BG_COLOR_STR_LMAGENTA      KTOSTRING(KTERMINAL_BG_COLOR_INT_LMAGENTA)
#define KTERMINAL_BG_COLOR_STR_LCYAN         KTOSTRING(KTERMINAL_BG_COLOR_INT_LCYAN)
#define KTERMINAL_BG_COLOR_STR_WHITE         KTOSTRING(KTERMINAL_BG_COLOR_INT_WHITE)

/* STR section, FORMAT ATTRIBUTES COLOR */
#define KTERMINAL_FORMAT_ATTR_STR_DEFAULT    KTOSTRING(KTERMINAL_FORMAT_ATTR_INT_DEFAULT)
#define KTERMINAL_FORMAT_ATTR_STR_BOLD       KTOSTRING(KTERMINAL_FORMAT_ATTR_INT_BOLD)
#define KTERMINAL_FORMAT_ATTR_STR_DIM        KTOSTRING(KTERMINAL_FORMAT_ATTR_INT_DIM)
#define KTERMINAL_FORMAT_ATTR_STR_UNDERLINED KTOSTRING(KTERMINAL_FORMAT_ATTR_INT_UNDERLINED)
#define KTERMINAL_FORMAT_ATTR_STR_BLINK      KTOSTRING(KTERMINAL_FORMAT_ATTR_INT_BLINK)

#define KTERMINAL_RESET_STR_ALL              "0"

#endif
